# !/bin/sh
# PARA COMPILAR: chmod +x nomePrograma
# PARA RODAR: ./nomePrograma

#TESTE DE CORES ANSI

#CORES DO TEXTO
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
MAGENTA='\e[35m'

LIGHT_RED='\e[91m'
LIGHT_GREEN='\e[92m'
LIGHT_YELLOW='\e[93m'
LIGHT_MAGENTA='\e[95m'

#CONTROLE DA SAIDA DE CORES
#OBS: DEVE SE COLOCAR ESSE COMANDO NO FIM DE CADA COR
STOP='\e[0m'

#TESTE DE SAIDA DE TEXTO COM AS CORES


#USANDO AS CORES ACIMA COMO VARIÁVEIS
T1="${RED}VERMELHO${STOP}"
T2="${GREEN}VERDE${STOP}"
T3="${LIGHT_YELLOW}AMARELO FRACO${STOP}"

#USANDO AS CORES COM AS VARIÁVEIS
T4='\e[33mAMARELO FORTE \e[0m'
T5='\e[91mVERMELHO FRACO \e[0m'

#SAIDA COM CHAMADA DE VARIAVEL
printf "${T1}\n${T2}\n${T3} \n"

#SAIDA COM AS CORES JUNTAS
printf "${T4} \n ${T5} \n"


